#!/usr/bin/env python3
"""Create a strict .codex_context layout for the trust-evidence-protocol plugin."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from context_lib import DEFAULT_SETTINGS


SCRIPT_DIR = Path(__file__).resolve().parent
PLUGIN_ROOT = SCRIPT_DIR.parent
TEMPLATES_ROOT = PLUGIN_ROOT / "templates" / "codex_context"

REQUIRED_DIRS = (
    "records/agent_identity",
    "records/workspace",
    "records/project",
    "records/input",
    "records/file",
    "records/run",
    "records/source",
    "records/claim",
    "records/permission",
    "records/restriction",
    "records/guideline",
    "records/proposal",
    "records/action",
    "records/task",
    "records/working_context",
    "records/curator_pool",
    "records/plan",
    "records/debt",
    "records/model",
    "records/flow",
    "records/open_question",
    "artifacts",
    "archives",
    "code_index/entries",
    "logic_index",
    "review",
    "runtime",
    "runtime/reasoning",
)


def write_text(path: Path, content: str, force: bool) -> None:
    if path.exists() and not force:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def bootstrap(target: Path, force: bool) -> None:
    for relative in REQUIRED_DIRS:
        (target / relative).mkdir(parents=True, exist_ok=True)

    readme = (TEMPLATES_ROOT / "README.md").read_text(encoding="utf-8")
    write_text(target / "README.md", readme, force=force)

    index_content = """# Codex Context Index

This index is informational only.

Canonical layers:
- `records/`
- `records/file/FILE-*.json` file metadata records
- `records/run/RUN-*.json` shell/tool execution records
- `artifacts/`
- `archives/` cleanup zip archives and manifests

Generated diagnostics:
- `review/broken.md`
- `review/stale.md`
- `review/conflicts.md`
- `review/models.md`
- `review/flows.md`
- `review/hypotheses.md`
- `review/resolved.md`
- `review/attention.md`
- active `PRP-*` proposals are surfaced in attention/brief views

Generated working views:
- `backlog.md`

Generated navigation layers:
- `code_index/entries/CIX-*.json`
- `code_index/by_path.json`
- `code_index/by_ref.json`
- `code_index/summary.md`
- `topic_index/`
- `logic_index/`

Runtime state:
- `runtime/hydration.json`
- `runtime/reasoning/reasons.jsonl` append-only REASON-* reasoning ledger
- current workspace pointer lives in `settings.json.current_workspace_ref`
- current project pointer lives in `settings.json.current_project_ref`
- current task pointer lives in `settings.json.current_task_ref`
- hook verbosity and context budget preferences live in `settings.json`
- `GRANT-*` TTL lives in `settings.json.chain_permits`
- input capture, artifact copy policy, and cleanup retention thresholds live in `settings.json`
- optional analysis backend policy for logic solver and topic prefilter lives in `settings.json.analysis`

Transient hypothesis index:
- `hypotheses.jsonl`

Templates live in the plugin, not in `.codex_context`.
"""
    write_text(target / "index.md", index_content, force=force)

    backlog_content = """# Active Backlog

This view is generated from canonical plan/debt records.
"""
    write_text(target / "backlog.md", backlog_content, force=force)

    settings_path = target / "settings.json"
    if force or not settings_path.exists():
        settings_path.write_text(
            json.dumps(DEFAULT_SETTINGS, indent=2) + "\n",
            encoding="utf-8",
        )

    hydration_path = target / "runtime" / "hydration.json"
    if force or not hydration_path.exists():
        hydration_path.write_text(
            json.dumps(
                {
                    "status": "unhydrated",
                    "updated_at": "1970-01-01T00:00:00+00:00",
                },
                indent=2,
            )
            + "\n",
            encoding="utf-8",
        )

    review_stub = """# Generated Review

This file is generated by plugin tooling.
Do not treat it as a source of truth.
"""
    write_text(target / "review" / "broken.md", review_stub, force=force)
    write_text(target / "review" / "stale.md", review_stub, force=force)
    write_text(target / "review" / "conflicts.md", review_stub, force=force)
    write_text(target / "review" / "models.md", review_stub, force=force)
    write_text(target / "review" / "flows.md", review_stub, force=force)
    write_text(target / "review" / "hypotheses.md", review_stub, force=force)
    write_text(target / "review" / "resolved.md", review_stub, force=force)
    write_text(target / "review" / "attention.md", review_stub, force=force)
    write_text(
        target / "code_index" / "summary.md",
        "# Code Index Summary\n\nThis navigation layer is generated from CIX-* entries and is not proof.\n",
        force=force,
    )
    write_text(
        target / "topic_index" / "summary.md",
        "# Topic Index Summary\n\nThis generated lexical pre-filter is navigation only and is not proof.\n",
        force=force,
    )
    write_text(
        target / "logic_index" / "summary.md",
        "# Logic Index Summary\n\nThis generated predicate pre-filter is navigation/checking only and is not proof.\n",
        force=force,
    )
    if force or not (target / "code_index" / "by_path.json").exists():
        (target / "code_index" / "by_path.json").write_text("{}\n", encoding="utf-8")
    if force or not (target / "code_index" / "by_ref.json").exists():
        (target / "code_index" / "by_ref.json").write_text("{}\n", encoding="utf-8")
    if force or not (target / "topic_index" / "records.json").exists():
        (target / "topic_index" / "records.json").write_text("{}\n", encoding="utf-8")
    if force or not (target / "topic_index" / "topics.json").exists():
        (target / "topic_index" / "topics.json").write_text("{}\n", encoding="utf-8")
    if force or not (target / "topic_index" / "by_record.json").exists():
        (target / "topic_index" / "by_record.json").write_text("{}\n", encoding="utf-8")
    if force or not (target / "topic_index" / "by_topic.json").exists():
        (target / "topic_index" / "by_topic.json").write_text("{}\n", encoding="utf-8")
    write_text(
        target / "topic_index" / "conflict_candidates.md",
        "# Topic Conflict Candidates\n\nThis generated view lists lexical candidates for review. It is not proof.\n",
        force=force,
    )
    logic_index_defaults = {
        "atoms.json": [],
        "symbols.json": {},
        "rules.json": [],
        "by_predicate.json": {},
        "by_symbol.json": {},
        "variable_graph.json": {
            "logic_graph_is_proof": False,
            "symbols": {},
            "predicates": {},
            "rules": {},
            "components": [],
            "smells": [],
        },
    }
    for name, default in logic_index_defaults.items():
        if force or not (target / "logic_index" / name).exists():
            (target / "logic_index" / name).write_text(json.dumps(default, indent=2) + "\n", encoding="utf-8")
    write_text(
        target / "logic_index" / "conflict_candidates.md",
        "# Logic Conflict Candidates\n\nThis generated view lists predicate-level candidates for review. It is not proof.\n",
        force=force,
    )
    write_text(
        target / "logic_index" / "vocabulary_smells.md",
        "# Logic Vocabulary Smells\n\nThis generated pressure report lists vocabulary graph smells. It is not proof.\n",
        force=force,
    )
    write_text(target / "hypotheses.jsonl", "", force=force)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Bootstrap a strict .codex_context layout.")
    parser.add_argument(
        "target",
        nargs="?",
        default=".codex_context",
        help="Target .codex_context directory (default: ./.codex_context)",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite README/index/review stubs when they already exist.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    target = Path(args.target).expanduser().resolve()
    bootstrap(target, force=args.force)
    print(f"Bootstrapped strict Codex context: {target}")


if __name__ == "__main__":
    main()
