"""Generated report rendering helpers."""

from __future__ import annotations

from pathlib import Path
from typing import Iterable

from .errors import ValidationError
from .io import write_text_file


def write_report(path: Path, title: str, intro: str, lines: Iterable[str]) -> None:
    content = [f"# {title}\n", "\n", f"{intro}\n", "\n"]
    rendered = list(lines)
    if not rendered:
        rendered = ["No issues found.\n"]
    content.extend(rendered)
    write_text_file(path, "".join(content))


def rel_display(root: Path, path: Path) -> str:
    try:
        return str(path.relative_to(root))
    except ValueError:
        return str(path)


def write_validation_report(root: Path, errors: list[ValidationError]) -> None:
    lines = [f"- `{rel_display(root, error.path)}`: {error.message}\n" for error in errors]
    write_report(
        root / "review" / "broken.md",
        "Generated Review",
        "This file is generated by plugin tooling. Do not treat it as a source of truth.",
        lines,
    )
